#!/usr/bin/env ruby

def find(option)
  regex_string = (option || "").strip
  
  if regex_string.start_with?("/")
    regex_string = regex_string[1..-1]
  end
  
  if regex_string.end_with?("/")
    regex_string = regex_string[0...-1]
  end
  
  regex = Regexp.new(regex_string)
  
  puts "\n\n#{regex}\n\n"
  
  routes = `bin/rake routes`.split("\n")
  
  matches = routes.select do |route|
    regex.match(route)
  end  
  
  puts matches
end  

option = ARGV[0]

case option
when "-h"
  puts ""
  puts "raigex -h        .... help menu"
  puts "raigex /[regex]/ .... regex search"
  puts ""
else
  find(option)
end

